server:
  servlet:
    context-path: /poli/api/v1
  port: 9080
spring:
  datasource:
    url: jdbc:h2:mem:tasks
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: todo-app2